### PR TITLE
Add client side query functionality

### PR DESCRIPTION
**Pull request by gabesullice**
This adds an interface to the Drupal Entity Query API module.

### CODE REVIEW

**Comment by mattgrill** [comment]
@gabesullice Hi! Thanks so much for submitting this.

There's a previous PR, #1 that restructures a bunch of how things work in Hydrant. I think we'll want to get this merged and then we can address how we want to introduce this work since it changes many things.

**Comment by mattgrill** [comment]
@gabesullice I fixed some of the issues blocking this in, https://github.com/prestonso/hydrant/tree/collections. I don't have access to push to your branch, but you could pull in the changes. If you would like, I can close this PR and re-open from the one in this repo.

 For this to work smoothly we should probably wait for #3 to be merged since I started from there.

**Comment by gabesullice** [comment]
@mattgrill merged your collections into mine. This PR can probably stay open for any work after #3 is merged.

**Comment by mattgrill** [comment]
@gabesullice 👍

**Comment by mattgrill** [comment]
@gabesullice I made some adjustments to the tests and cleaned a few things up. Overall I'm very excited to get this merged.

**Comment by prestonso** [comment]
I'm reviewing this now.

**Comment by prestonso** [comment]
Reviewing this now.

**Comment by prestonso** [comment]
The code looks good to me.

@mattgrill confirmed that this is working locally, so I am eschewing a test for now.

LGTM :shipit:

**Pull request merged**
